#!/usr/bin/env sh

# Dependencies:
#
# cargo install watchexec

# Assumes you have `local-bin-path: .bin` set in your ~/.stack/config.yaml`.

case $1 in
  "stack")
    stack build --fast --file-watch --test --copy-bins
    ;;

  "lunar")
    watchexec --restart './.bin/bowtie example-app/lunar-lander.bowtie' --watch .bin/bowtie --watch example-app --watch example-lib
    ;;

  "lunar-js")
    ./.bin/bowtie-js example-app/lunar-lander.bowtie > unpretty.js
    prettier unpretty.js > bowtie-js/main.js
    ;;

  *)
    echo "dev: no argument match"
    ;;
esac
