name: bowtie
default-extensions:
  # NOTE: Keep in sync with ./doctest/DocTest.hs and ./.stylish-haskell.yaml

  # Notable

  - StrictData

  # Other

  - BlockArguments
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables

ghc-options: -Wall
dependencies:

  # Notable

  - megaparsec
  - parser-combinators

  # Other

  - base
  - bytestring
  - containers
  - deepseq
  - directory
  - filepath
  - hashable
  - mtl
  - safe
  - text
  - transformers
  - unordered-containers
  - unordered-containers
  - writer-cps-mtl
  - writer-cps-transformers

extra-doc-files: doc.md

library:
  source-dirs: src

executables:
  bowtie:
    source-dirs: .
    main: Main.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - bowtie
      - optparse-applicative

tests:
  doctest:
    source-dirs: doctest
    main: DocTest.hs
    dependencies:
      - bowtie
      - doctest
      - Glob

  spec:
    source-dirs: test
    main: Test.hs
    dependencies:
      - bowtie
      - bowtie-example
      - hspec
      - QuickCheck
      - template-haskell
